apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-php7-server
  labels:
    app: my-php7-server
spec:
  template:
    metadata:
      labels:
        app: my-php7-server
    spec:
      containers:
      - name: my-php7-server
        image: docker.io/spolise/php-frontend:002
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_NAME
          value: mysql
        - name: DB_USER
          value: todos-user
        - name: DB_ROOT_PWD
          value: dummypassword
        - name: DB_PWD
          value: dummytodos
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: my-php7-server
spec:
  type: LoadBalancer
  selector:
    app: my-php7-server
  ports:
    - name: php
      protocol: TCP
      port: 80
      targetPort: 80
